# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://quantumgame.io
title: Quantum Game with Photons
email: pmigdal@gmail.com
thumbnail: /img/services/gameplay.png
author: Piotr Migdał
description: A puzzle game with photons, superposition and quantum measurement, right in your browser. With true quantum mechanics underneath!
copyright: "Copyright &copy; 2016 Piotr Migdał. All Rights Reserved."
credits: 'Style based on a open Jekyll theme <a href="http://startbootstrap.com/">Start Bootstrap: Landing Page</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    icon: github
    url: https://github.com/stared/quantum-game
  - title: facebook
    icon: facebook
    url: https://www.facebook.com/quantumgameio
  - title: twitter
    icon: twitter
    url: https://twitter.com/QuantumFlytrap
  - title: subscribe
    icon: envelope
    url: http://quantumgame.us9.list-manage.com/subscribe?u=5e3bdb13b61924c4b0ec92fba&id=e1c573b8d3
